<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Jaga-Laptop" failures="1" tests="1" name="com.qa.test.runner.TestRunner" time="4.998" errors="0" timestamp="10 Sep 2021 12:35:12 GMT" skipped="0">
  <testcase classname="com.qa.test.runner.TestRunner" name="runScenario" time="4.998">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertFalse(Assert.java:65)
at org.testng.Assert.assertFalse(Assert.java:75)
at com.qa.test.base.TestBase.invokeBrowser(TestBase.java:62)
at com.qa.test.base.TestBase.before(TestBase.java:71)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- com.qa.test.runner.TestRunner -->
